#!/usr/bin/env python3
"""
NirmanAI - GGUF & Merged Model Exporter
======================================
Merges the fine-tuned LoRA adapter into the base model and exports it
to 4-bit GGUF format for ultra-fast local inference on CPU/RAM via Ollama.

Usage:
  python training/export_gguf.py
  python training/export_gguf.py --quantization q4_k_m --output_file nirmanai-7b.gguf
"""

import argparse
import os
import sys
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def parse_args():
    parser = argparse.ArgumentParser(description="Export NirmanAI model to GGUF format")
    parser.add_argument(
        "--adapter_dir",
        type=str,
        default="./nirmanai_adapter",
        help="Path to trained LoRA adapter directory",
    )
    parser.add_argument(
        "--cache_dir",
        type=str,
        default="D:/NirmanAI_Models/hf_cache",
        help="Directory to cache Hugging Face downloads",
    )
    parser.add_argument(
        "--merged_dir",
        type=str,
        default="D:/NirmanAI_Models/merged_16bit",
        help="Target directory to save merged 16-bit model",
    )
    parser.add_argument(
        "--modelfile_out",
        type=str,
        default="D:/NirmanAI_Models/Modelfile",
        help="Path to generate Ollama Modelfile",
    )
    return parser.parse_args()


def export():
    args = parse_args()
    print("=" * 80)
    print("           NIRMAN-AI : LORA MERGER & OLLAMA MODEL PREPARER")
    print("=" * 80)

    adapter_path = Path(args.adapter_dir)
    if not adapter_path.exists():
        print(f"❌ Error: Adapter directory not found at: {adapter_path}")
        print("Please train the model first using 'python training/train_nirmanai.py'.")
        sys.exit(1)

    os.environ["HF_HOME"] = str(args.cache_dir)
    os.makedirs(args.cache_dir, exist_ok=True)
    os.makedirs(args.merged_dir, exist_ok=True)

    import torch
    from peft import PeftModel
    from transformers import AutoModelForCausalLM, AutoTokenizer

    print(f"📂 HF Cache Directory:    {args.cache_dir}")
    print(f"📂 Merged Model Target:   {args.merged_dir}")
    print(f"📂 Base Model:            Qwen/Qwen2.5-7B-Instruct")
    print("-" * 80)

    print("1/4 Loading Tokenizer from adapter...")
    tokenizer = AutoTokenizer.from_pretrained(str(adapter_path), trust_remote_code=True)

    print("2/4 Loading Base Model (float16) to D: drive...")
    dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    base_model = AutoModelForCausalLM.from_pretrained(
        "Qwen/Qwen2.5-7B-Instruct",
        torch_dtype=dtype,
        device_map="auto",
        cache_dir=str(args.cache_dir),
        trust_remote_code=True,
    )

    print("3/4 Applying LoRA Adapter and Merging Weights...")
    model = PeftModel.from_pretrained(base_model, str(adapter_path))
    merged_model = model.merge_and_unload()

    print(f"4/4 Saving Merged Standalone Model to {args.merged_dir}...")
    merged_model.save_pretrained(args.merged_dir)
    tokenizer.save_pretrained(args.merged_dir)
    print(f"✅ Merged model successfully saved to: {args.merged_dir}")

    # Generate Ollama Modelfile
    modelfile_path = Path(args.modelfile_out)
    merged_posix = Path(args.merged_dir).as_posix()
    modelfile_content = f"""# NirmanAI Ollama Modelfile
# Auto-generated by export_gguf.py

FROM {merged_posix}

PARAMETER temperature 0.2
PARAMETER top_p 0.9
PARAMETER stop "<|im_end|>"
PARAMETER stop "<|endoftext|>"

SYSTEM \"\"\"You are NirmanAI, an autonomous distributed systems architect. Analyze the user's requirements and produce a production-grade, highly scalable system architecture dossier including system overview, capacity planning calculations, visual Mermaid diagram, component breakdown, architectural trade-offs, and bottleneck mitigation strategies.\"\"\"
"""
    with open(modelfile_path, "w", encoding="utf-8") as f:
        f.write(modelfile_content)

    print(f"✅ Ollama Modelfile created at: {modelfile_path}")
    print("=" * 80)
    print("\n🚀 Next Step: Register model in Ollama by running:")
    print(f"   ollama create nirmanai:7b -f {modelfile_path}\n")
    print("=" * 80)


if __name__ == "__main__":
    export()
