"""
NirmanAI - Generator Schema
===========================
Defines the component graph, communication protocols, technologies,
and topology generated by the fine-tuned architecture model.
"""

from enum import Enum
from typing import List, Dict, Optional
from pydantic import BaseModel, Field


class LayerType(str, Enum):
    CLIENT = "Client & Perimeter Layer"
    INGRESS = "Edge Ingress & Security Layer"
    COMPUTE = "Stateless Microservices Compute Tier"
    EVENT_BUS = "Asynchronous Streaming & Event Bus Tier"
    PERSISTENCE = "Polyglot Persistent Datastore Tier"
    CACHE = "Distributed In-Memory Caching Tier"
    ML_PIPELINE = "AI/ML Inference & Real-Time Analytics Tier"
    INFRASTRUCTURE = "Observability, Telemetry & Disaster Recovery Tier"


class CommunicationProtocol(str, Enum):
    HTTPS_REST = "HTTPS / TLS 1.3 (REST/JSON)"
    GRPC = "gRPC / HTTP/2 (Protocol Buffers)"
    WEBSOCKET = "WebSocket (Bi-directional Streaming)"
    KAFKA_TOPIC = "Kafka Topic Pub/Sub"
    AMQP = "AMQP / RabbitMQ Event Queue"
    GRAPHQL = "GraphQL over HTTPS"


class ComponentNode(BaseModel):
    id: str = Field(..., description="Unique node ID in graph (e.g. 'API_GW', 'AUTH_SVC')")
    name: str = Field(..., description="Human-readable component name")
    layer: LayerType = Field(..., description="Architectural tier/subgraph layer")
    technology: str = Field(..., description="Selected technology (e.g. 'Envoy Gateway', 'Kafka', 'PostgreSQL')")
    purpose: str = Field(..., description="Core responsibility in system")
    scaling_strategy: str = Field(default="Horizontal Pod Autoscaling (CPU/Memory triggers)", description="How this component scales")
    is_stateful: bool = Field(default=False, description="True if stateful storage; False if stateless compute")
    redundancy: str = Field(default="Multi-AZ Active-Active Replication", description="Failover and replication model")


class ConnectionEdge(BaseModel):
    source_id: str = Field(..., description="Source component node ID")
    target_id: str = Field(..., description="Target component node ID")
    protocol: CommunicationProtocol = Field(default=CommunicationProtocol.GRPC, description="Communication protocol")
    description: str = Field(..., description="Payload or action description (e.g. 'order.created event')")
    is_synchronous: bool = Field(default=True, description="True if blocking RPC; False if async fire-and-forget")


class SystemArchitecture(BaseModel):
    system_name: str = Field(..., description="System name / title")
    domain: str = Field(..., description="Domain category")
    style: str = Field(..., description="Architectural style")
    cloud: str = Field(..., description="Deployment cloud")
    overview: str = Field(..., description="Comprehensive architectural narrative")
    components: List[ComponentNode] = Field(default_factory=list, description="All architectural component nodes")
    connections: List[ConnectionEdge] = Field(default_factory=list, description="All service-to-service communication edges")
    mermaid_diagram: str = Field(..., description="Full production-grade Mermaid.js code")
    technology_stack: Dict[str, str] = Field(default_factory=dict, description="Key technology mappings (Gateway, DB, Cache, etc.)")
    trade_offs: List[str] = Field(
        default_factory=list,
        description="Concrete architectural trade-offs specific to this system design (e.g., 'Chose eventual consistency over strong consistency for notification fanout to achieve sub-100ms delivery at cost of 2-5s stale reads.')"
    )
    bottleneck_mitigations: List[str] = Field(
        default_factory=list,
        description="Identified bottlenecks and their specific mitigations (e.g., 'Bottleneck: Single PostgreSQL writer under 50k TPS peak. Mitigation: Citus horizontal sharding with consistent hash on user_id across 8 shard nodes.')"
    )
