"""
NirmanAI - Architecture Enhancer Agent
=======================================
Takes the raw output from the fine-tuned local model (domain-specific skeleton
with 6 components, basic Mermaid, and trade-offs) and enhances it into a
production-grade SystemArchitecture via Gemini.

Design Pattern: Draft → Refine
- Fine-tuned model provides: domain-specific component choices, base Mermaid,
  architecture patterns learned from 20k training examples
- Gemini Enhancement provides: schema compliance, missing layers, deeper
  trade-offs with numbers, proper connections with protocols

This is NOT a wrapper — the fine-tuned model's domain knowledge genuinely
improves the final output vs Gemini generating from scratch on a vague prompt.
"""

import json
import logging
from typing import Optional

from nirman.agents.gemini_client import GeminiClient
from nirman.schemas.generator import SystemArchitecture
from nirman.schemas.analyzer import RequirementSpec
from nirman.schemas.estimator import CapacityMetrics

logger = logging.getLogger("nirman.agents.enhancer_arch")


ENHANCER_SYSTEM_PROMPT = """You are NirmanAI's Architecture Enhancement Agent.

You receive TWO inputs:
1. A BASE ARCHITECTURE generated by a domain-specialized fine-tuned model (trained on 20,000 system architecture examples)
2. The ORIGINAL user prompt

Your job is to ENHANCE the base architecture — NOT replace it. The fine-tuned model's output contains valuable domain-specific component choices and patterns. You must:

KEEP & RESPECT:
- ALL components from the base architecture (they are domain-specific and intentional)
- The core technology choices (the fine-tuned model picked them for good reasons)
- The architectural style and domain context

ENHANCE & ADD:
- Expand from the base components to 12-15 total components by adding missing architectural layers:
  * If missing: Observability stack (Prometheus + Grafana + Jaeger)
  * If missing: Authentication/Authorization service (Keycloak/Auth0)
  * If missing: CDN/Edge caching layer
  * If missing: Data lake / analytics pipeline
  * If missing: Disaster recovery / backup strategy component
  * If missing: Service mesh / sidecar proxy
- Add 8-12 specific ConnectionEdge objects with real protocols (gRPC, REST, Kafka, WebSocket)
- Deepen trade_offs to 3-5 SPECIFIC decisions with component names and quantitative impact
- Deepen bottleneck_mitigations to 3-4 SPECIFIC bottlenecks with numbers
- Fill in proper scaling_strategy and redundancy for each component
- Build a complete technology_stack mapping

MERMAID DIAGRAM REQUIREMENTS (VERY IMPORTANT):
Generate a RICH, DETAILED Mermaid flowchart with these rules:
1. Each node MUST include a one-liner description using <br/> tag:
   GOOD: API_GW["API Gateway<br/>Rate limiting, TLS termination, auth routing"]
   GOOD: KAFKA["Apache Kafka<br/>3-broker cluster, 100K msg/sec throughput"]
   BAD:  API_GW["API Gateway"]  (too simple, no description)

2. Use subgraphs for EACH architectural layer with clear titles

3. Edge labels MUST show the protocol AND data flowing:
   GOOD: API_GW -->|"REST/TLS 1.3 - Auth tokens"| AUTH_SVC
   GOOD: FANOUT -->|"Kafka topic: msg.created"| KAFKA
   BAD:  API_GW --> AUTH_SVC  (no label)

4. Add MORE connections to show the REAL complexity:
   - Data flows (reads, writes, events)
   - Control flows (health checks, circuit breakers)
   - Async flows (event streaming, pub/sub)
   - Monitoring flows (metrics, traces, logs)

5. Use different edge styles for sync vs async:
   - Sync: -->|"label"| (solid arrow)
   - Async: -.->|"label"| (dotted arrow for events/queues)

6. Minimum 15 connections in the diagram showing real inter-service communication

7. ASCII only - no unicode characters. No special chars in labels without quotes.

8. DARK COLOR THEME - Add these classDef styles at the TOP of the diagram and apply them:
   classDef client fill:#1a1a2e,stroke:#e94560,color:#ffffff,stroke-width:2px
   classDef ingress fill:#16213e,stroke:#0f3460,color:#ffffff,stroke-width:2px
   classDef compute fill:#0f3460,stroke:#533483,color:#ffffff,stroke-width:2px
   classDef eventbus fill:#1b1b2f,stroke:#1f4068,color:#e94560,stroke-width:2px
   classDef datastore fill:#162447,stroke:#e94560,color:#ffffff,stroke-width:2px
   classDef cache fill:#533483,stroke:#e94560,color:#ffffff,stroke-width:2px
   classDef ml fill:#1f4068,stroke:#533483,color:#ffffff,stroke-width:2px
   classDef infra fill:#0a0a23,stroke:#1f4068,color:#00d2ff,stroke-width:2px

   Apply classes using the :::className syntax on each node:
   - Client/CDN/WAF nodes: :::client
   - API Gateway/Auth nodes: :::ingress
   - Microservices/compute nodes: :::compute
   - Kafka/queues/event nodes: :::eventbus
   - Database/storage nodes: :::datastore
   - Redis/cache nodes: :::cache
   - ML/Analytics nodes: :::ml
   - Observability/DR/infra nodes: :::infra

   Example: API_GW["API Gateway<br/>Rate limiting, TLS termination"]:::ingress

OUTPUT: Return a COMPLETE SystemArchitecture JSON object matching the schema exactly.

CRITICAL RULES:
- Mermaid diagram must use ASCII hyphens only (- not unicode dashes)
- Node labels with special characters must be quoted: id["Label (Extra)"]
- All component IDs must be UPPER_SNAKE_CASE (e.g., API_GW, AUTH_SVC)
- Connections must reference valid component IDs
- trade_offs and bottleneck_mitigations must be List[str], not a single string
"""


class ArchitectureEnhancerAgent:
    """Enhances a fine-tuned model's raw architecture output into production-grade SystemArchitecture.
    
    Agent Capabilities:
    - Takes raw dict from fine-tuned model (component_breakdown, mermaid_diagram, etc.)
    - Sends it to Gemini with the original user prompt for context
    - Gemini keeps domain-specific components and adds missing layers
    - Returns a validated SystemArchitecture Pydantic object
    - Retry with self-correction on validation failure
    """

    MAX_RETRIES = 2

    def __init__(self, gemini_client: Optional[GeminiClient] = None):
        self.client = gemini_client or GeminiClient()

    def enhance(
        self,
        raw_model_output: dict,
        original_prompt: str,
        spec: Optional[RequirementSpec] = None,
        capacity: Optional[CapacityMetrics] = None,
    ) -> SystemArchitecture:
        """Enhance the fine-tuned model's raw output into a full SystemArchitecture.
        
        Args:
            raw_model_output: Raw dict from fine-tuned model with keys like
                system_overview, component_breakdown, mermaid_diagram, trade_offs, etc.
            original_prompt: The user's original prompt for context
            spec: Optional RequirementSpec from the Analyzer phase
            capacity: Optional CapacityMetrics from the Estimator phase
            
        Returns:
            A validated SystemArchitecture Pydantic object with 12+ components
        """
        # Format the base architecture for Gemini
        base_arch_text = self._format_base_architecture(raw_model_output)
        
        # Build context-rich user prompt
        context_parts = [
            f"ORIGINAL USER PROMPT: {original_prompt}",
            "",
            f"BASE ARCHITECTURE FROM FINE-TUNED MODEL:",
            base_arch_text,
        ]
        
        if spec:
            context_parts.extend([
                "",
                f"ANALYZED REQUIREMENTS:",
                f"- Domain: {spec.domain.value}",
                f"- Cloud: {spec.cloud_provider.value}",
                f"- Style: {spec.preferred_style.value}",
                f"- Functional Requirements: {', '.join([fr.title for fr in spec.functional_requirements[:5]])}",
                f"- Non-Functional Requirements: {', '.join([nfr.target_metric for nfr in spec.non_functional_requirements[:4]])}",
            ])
        
        if capacity:
            context_parts.extend([
                "",
                f"CAPACITY CONSTRAINTS:",
                f"- DAU: {capacity.traffic.dau:,}",
                f"- Peak QPS: {capacity.traffic.peak_qps:,}",
                f"- 5-Year Storage: {capacity.storage.effective_5yr_storage_tb:.1f} TB",
                f"- Cache: {capacity.cache.cache_memory_ram_gb:.0f} GB RAM ({capacity.cache.recommended_nodes} nodes)",
                f"- Compute Pods: ~{capacity.recommended_compute_pods}",
            ])
        
        context_parts.append("")
        context_parts.append(
            "ENHANCE this base architecture into a production-grade SystemArchitecture. "
            "Keep all existing components and add missing layers to reach 12-15 total components. "
            "Generate clean Mermaid diagram with subgraphs. Add detailed connections with protocols."
        )
        
        user_prompt = "\n".join(context_parts)
        
        last_error = None
        for attempt in range(1, self.MAX_RETRIES + 1):
            try:
                logger.info(f"Enhancement attempt {attempt}/{self.MAX_RETRIES}...")
                
                arch = self.client.generate_structured(
                    system_prompt=ENHANCER_SYSTEM_PROMPT,
                    user_prompt=user_prompt,
                    schema=SystemArchitecture,
                )
                
                # Validate enhancement quality
                issues = self._validate_enhancement(arch, raw_model_output)
                if issues:
                    issues_str = "; ".join(issues)
                    logger.warning(f"Enhancement validation issues (attempt {attempt}): {issues_str}")
                    if attempt < self.MAX_RETRIES:
                        user_prompt = (
                            f"Your previous enhancement had these issues: {issues_str}\n"
                            f"Please fix them.\n\n{user_prompt}"
                        )
                        continue
                    else:
                        logger.warning("Max retries reached. Using enhancement despite issues.")
                
                # Sanitize Mermaid diagram
                arch.mermaid_diagram = self._sanitize_mermaid(arch.mermaid_diagram)
                
                logger.info(
                    f"Enhancement complete: {len(arch.components)} components, "
                    f"{len(arch.connections)} connections, "
                    f"{len(arch.trade_offs)} trade-offs, "
                    f"{len(arch.bottleneck_mitigations)} mitigations"
                )
                return arch
                
            except Exception as e:
                last_error = e
                logger.error(f"Enhancement attempt {attempt} failed: {e}")
                if attempt < self.MAX_RETRIES:
                    continue
        
        raise RuntimeError(
            f"ArchitectureEnhancerAgent failed after {self.MAX_RETRIES} attempts. "
            f"Last error: {last_error}"
        )

    def _format_base_architecture(self, raw: dict) -> str:
        """Format the raw fine-tuned model output as readable text for Gemini."""
        parts = []
        
        if raw.get("system_overview"):
            parts.append(f"System Overview: {raw['system_overview']}")
        
        if raw.get("capacity_planning"):
            cp = raw["capacity_planning"]
            if isinstance(cp, dict):
                parts.append(f"Capacity: DAU={cp.get('dau', 'N/A')}, Peak QPS={cp.get('peak_qps', 'N/A')}, Storage={cp.get('storage_per_year', 'N/A')}")
        
        if raw.get("component_breakdown"):
            parts.append("Components from fine-tuned model:")
            for i, comp in enumerate(raw["component_breakdown"], 1):
                if isinstance(comp, dict):
                    parts.append(f"  {i}. {comp.get('name', '?')} - Tech: {comp.get('tech', '?')} - Rationale: {comp.get('rationale', '?')}")
                else:
                    parts.append(f"  {i}. {comp}")
        
        if raw.get("mermaid_diagram"):
            parts.append(f"Base Mermaid Diagram:\n{raw['mermaid_diagram']}")
        
        if raw.get("trade_offs"):
            parts.append(f"Base Trade-offs: {raw['trade_offs']}")
        
        if raw.get("bottlenecks_and_mitigation"):
            parts.append(f"Base Bottleneck Mitigations: {raw['bottlenecks_and_mitigation']}")
        
        return "\n".join(parts)

    def _validate_enhancement(self, arch: SystemArchitecture, raw_base: dict) -> list:
        """Validate that the enhancement actually improved the base architecture."""
        issues = []
        
        base_comp_count = len(raw_base.get("component_breakdown", []))
        
        if len(arch.components) < 8:
            issues.append(f"Expected at least 8 components after enhancement, got {len(arch.components)}")
        
        if len(arch.components) <= base_comp_count:
            issues.append(
                f"Enhancement should ADD components. Base had {base_comp_count}, "
                f"enhanced has {len(arch.components)}. Add missing layers."
            )
        
        if len(arch.connections) < 5:
            issues.append(f"Expected at least 5 connections, got {len(arch.connections)}")
        
        if len(arch.trade_offs) < 2:
            issues.append(f"Expected at least 2 trade-offs, got {len(arch.trade_offs)}")
        
        if not arch.mermaid_diagram or len(arch.mermaid_diagram.splitlines()) < 10:
            issues.append("Mermaid diagram too short or missing")
        
        if not arch.overview or len(arch.overview) < 50:
            issues.append("Overview is too short")
        
        return issues

    @staticmethod
    def _sanitize_mermaid(diagram: str) -> str:
        """Sanitize Mermaid diagram for clean browser rendering.
        
        Fixes:
        - Unicode non-breaking hyphens (U+2011) → ASCII hyphen
        - Unicode dashes (em/en dash) → ASCII hyphen
        - Unquoted node labels with special characters
        - Literal \\n in labels → <br/>
        """
        import re
        
        if not diagram:
            return diagram
        
        # Replace unicode hyphens/dashes with ASCII
        sanitized = diagram.replace('\u2011', '-')  # non-breaking hyphen
        sanitized = sanitized.replace('\u2013', '-')  # en dash
        sanitized = sanitized.replace('\u2014', '-')  # em dash
        sanitized = sanitized.replace('\u2010', '-')  # hyphen
        sanitized = sanitized.replace('\u00AD', '-')  # soft hyphen
        
        # Fix literal \n in labels
        sanitized = sanitized.replace('\\n', '<br/>')
        
        # Quote unquoted labels with special chars
        def quote_label(match):
            prefix = match.group(1)
            label = match.group(2)
            suffix = match.group(3)
            if any(c in label for c in '()&/'):
                return f'{prefix}"{label}"{suffix}'
            return match.group(0)
        
        sanitized = re.sub(
            r'(\[)([^\]"]+)(\])',
            quote_label,
            sanitized
        )
        
        return sanitized
